[tool.poetry]
name = "station-randomizer"
version = "0.1.0"
description = ""
authors = ["maxomm <max.warsinke@googlemail.com>"]
readme = "README.md"
packages = [{include = "station_randomizer"}]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
